kotlin.code.style=official
org.gradle.jvmargs=-Xmx8G

# Fabric Properties
# Check these on https://fabricmc.net/versions.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Fabric API
fabric_version=0.118.0+1.21.4

# Loom
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.21.4-1.7.0
maven_group=net.devoev
modid=vanilla_cubed
archives_base_name=vanilla-cubed

# Kotlin
kotlin_version=2.1.10
fabric_kotlin_version=1.13.1+kotlin.2.1.10

# Other dependencies
reach_entity_attribute_version=2.4.0